#!/bin/sh

. /usr/local/lib/cont-init-functions.sh
ENSURE_DIR_MODE=2755
ENSURE_DIR_USER=shepherd
ENSURE_DIR_GROUP=nogroup

ensure_dir /run/shepherd
ensure_dir /local/shepherd
ensure_dir /local/shepherd/static
ensure_dir /local/shepherd/media

# Ensure group permissions
sock=/var/run/docker.sock
gid=$(stat -c '%g' $sock)
gname=$(getent group "$gid")
[ "$gname" ] || groupadd -g "$gid" docker_socket
usermod -G "$gid" grader